### ISSUE TITLE
bug with leaderheads plugin

### ISSUE THREAD

**Issue by Yukyxy** [ezeiger92/QuestWorld2#100]
Hello
Can you make it compatible?

[12:46:38] [Craft Scheduler Thread - 241/ERROR]: [LeaderHeads] Error while updating the qw-quests statistic
java.lang.NoClassDefFoundError: me/mrCookieSlime/QuestWorld/QuestWorld
at me.robin.leaderheads.datacollectors.b4.a.getScore(a.java:2) ~[LeaderHeads.jar:?]
at me.robin.leaderheads.datacollectors.OnlineDataCollector.requestAll(OnlineDataCollector.java:59) [LeaderHeads.jar:?]
at me.robin.leaderheads.datacollectors.cv.o(cv.java:232) [LeaderHeads.jar:?]
at me.robin.leaderheads.datacollectors.c9.run(c9.java:3) [LeaderHeads.jar:?]
at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71) [spigot-1.12.jar:git-Spigot-ede465d-bb4ae3b]
at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [spigot-1.12.jar:git-Spigot-ede465d-bb4ae3b]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_72]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_72]
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72]

**Comment by ezeiger92** [comment]
This is not a bug, as it's hardly the same plugin it used to be. At any rate I've contacted RobiRami to see if we can make this work.

**Comment by Yukyxy** [comment]
version mc 1.12
I already wrote to RobiRami...

his answer:
"Use an older version and ask their developer to make it backwards compatible."

**Comment by ezeiger92** [comment]
I can’t make it backwards compatible unless I know what code he’s trying to use, which is why I contacted him. Haven’t heard back yet.

**Comment by Yukyxy** [comment]
ok^^ i wait

**Comment by ezeiger92** [comment]
After 2 days of no reply and no access to his plugin, I went and found a cracked version and decompiled it to look at the QuestWorld code used. Go ahead and try this version to see if it works.

[QuestWorld-2.6.10.1-SNAPSHOT.jar.zip](https://github.com/ezeiger92/QuestWorld2/files/1701448/QuestWorld-2.6.10.1-SNAPSHOT.jar.zip)

**Comment by Yukyxy** [comment]
oh thank you it works, and I no longer have the error messages thank you
