### ISSUE TITLE
Exception using death reset

### ISSUE THREAD

**Issue by rxsglzc** [ezeiger92/QuestWorld2#103]
Hello, Dear Author 
There is a small problem with QuestBook.  I'm in spigot-1.11.2 and QuestWorld-2.6.10.when book: on-first-join: true  .players could not get a book and have error report. try to the command 'questeditor book' also have error..........The problem is not in spigot-1.12.2
```Could not pass event PlayerJoinEvent to QuestWorld v2.6.10
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.11.2-R0.1-SNAPSHOT.jar:git-Spigot-3fb9445-2b6c9f4]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.11.2-R0.1-SNAPSHOT.jar:git-Spigot-3fb9445-2b6c9f4]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.11.2-R0.1-SNAPSHOT.jar:git-Spigot-3fb9445-2b6c9f4]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.11.2-R0.1-SNAPSHOT.jar:git-Spigot-3fb9445-2b6c9f4]
	at net.minecraft.server.v1_11_R1.PlayerList.onPlayerJoin(PlayerList.java:327) [spigot-1.11.2-R0.1-SNAPSHOT.jar:git-Spigot-3fb9445-2b6c9f4]
	at net.minecraft.server.v1_11_R1.PlayerList.a(PlayerList.java:160) [spigot-1.11.2-R0.1-SNAPSHOT.jar:git-Spigot-3fb9445-2b6c9f4]
	at net.minecraft.server.v1_11_R1.LoginListener.b(LoginListener.java:147) [spigot-1.11.2-R0.1-SNAPSHOT.jar:git-Spigot-3fb9445-2b6c9f4]
	at net.minecraft.server.v1_11_R1.LoginListener.F_(LoginListener.java:57) [spigot-1.11.2-R0.1-SNAPSHOT.jar:git-Spigot-3fb9445-2b6c9f4]
	at net.minecraft.server.v1_11_R1.NetworkManager.a(NetworkManager.java:233) [spigot-1.11.2-R0.1-SNAPSHOT.jar:git-Spigot-3fb9445-2b6c9f4]
	at net.minecraft.server.v1_11_R1.ServerConnection.c(ServerConnection.java:140) [spigot-1.11.2-R0.1-SNAPSHOT.jar:git-Spigot-3fb9445-2b6c9f4]
	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:842) [spigot-1.11.2-R0.1-SNAPSHOT.jar:git-Spigot-3fb9445-2b6c9f4]
	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot-1.11.2-R0.1-SNAPSHOT.jar:git-Spigot-3fb9445-2b6c9f4]
	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:678) [spigot-1.11.2-R0.1-SNAPSHOT.jar:git-Spigot-3fb9445-2b6c9f4]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:576) [spigot-1.11.2-R0.1-SNAPSHOT.jar:git-Spigot-3fb9445-2b6c9f4]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_161]
Caused by: java.lang.NoClassDefFoundError: org/bukkit/NamespacedKey
	at me.mrCookieSlime.QuestWorld.GuideBook.<init>(GuideBook.java:19) ~[?:?]
	at me.mrCookieSlime.QuestWorld.GuideBook.instance(GuideBook.java:23) ~[?:?]
	at me.mrCookieSlime.QuestWorld.GuideBook.get(GuideBook.java:29) ~[?:?]
	at me.mrCookieSlime.QuestWorld.listener.PlayerListener.onJoin(PlayerListener.java:66) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_161]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_161]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_161]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_161]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot-1.11.2-R0.1-SNAPSHOT.jar:git-Spigot-3fb9445-2b6c9f4]
	... 14 more`
-------------------
`null
org.bukkit.command.CommandException: Unhandled exception executing command 'questeditor' in plugin QuestWorld v2.6.10
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot-1.11.2-R0.1-SNAPSHOT.jar:git-Spigot-3fb9445-2b6c9f4]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot-1.11.2-R0.1-SNAPSHOT.jar:git-Spigot-3fb9445-2b6c9f4]
	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.dispatchCommand(CraftServer.java:650) ~[spigot-1.11.2-R0.1-SNAPSHOT.jar:git-Spigot-3fb9445-2b6c9f4]
	at net.minecraft.server.v1_11_R1.PlayerConnection.handleCommand(PlayerConnection.java:1354) [spigot-1.11.2-R0.1-SNAPSHOT.jar:git-Spigot-3fb9445-2b6c9f4]
	at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:1189) [spigot-1.11.2-R0.1-SNAPSHOT.jar:git-Spigot-3fb9445-2b6c9f4]
	at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot-1.11.2-R0.1-SNAPSHOT.jar:git-Spigot-3fb9445-2b6c9f4]
	at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot-1.11.2-R0.1-SNAPSHOT.jar:git-Spigot-3fb9445-2b6c9f4]
	at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.11.2-R0.1-SNAPSHOT.jar:git-Spigot-3fb9445-2b6c9f4]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_161]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_161]
	at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46) [spigot-1.11.2-R0.1-SNAPSHOT.jar:git-Spigot-3fb9445-2b6c9f4]
	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:747) [spigot-1.11.2-R0.1-SNAPSHOT.jar:git-Spigot-3fb9445-2b6c9f4]
	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot-1.11.2-R0.1-SNAPSHOT.jar:git-Spigot-3fb9445-2b6c9f4]
	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:678) [spigot-1.11.2-R0.1-SNAPSHOT.jar:git-Spigot-3fb9445-2b6c9f4]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:576) [spigot-1.11.2-R0.1-SNAPSHOT.jar:git-Spigot-3fb9445-2b6c9f4]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_161]
Caused by: java.lang.NoClassDefFoundError: org/bukkit/NamespacedKey
	at me.mrCookieSlime.QuestWorld.GuideBook.<init>(GuideBook.java:19) ~[?:?]
	at me.mrCookieSlime.QuestWorld.GuideBook.instance(GuideBook.java:23) ~[?:?]
	at me.mrCookieSlime.QuestWorld.GuideBook.get(GuideBook.java:29) ~[?:?]
	at me.mrCookieSlime.QuestWorld.command.EditorCommand.onCommand(EditorCommand.java:96) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot-1.11.2-R0.1-SNAPSHOT.jar:git-Spigot-3fb9445-2b6c9f4]
	... 15 more
```

**Comment by ezeiger92** [comment]
Bukkit 1.12.2 is the only supported version, sorry. That stacktrace is caused by use of a class that was only added in bukkit 1.12 (NamespacedKey).

**Comment by rxsglzc** [comment]
Another problem, When a task is set up Resets On Death, then player dies, there is error and 'Resets On Death' not work.
`Could not pass event PlayerDeathEvent to QuestWorld v2.6.10
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.11.2-R0.1-SNAPSHOT.jar:git-Spigot-3fb9445-2b6c9f4]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.11.2-R0.1-SNAPSHOT.jar:git-Spigot-3fb9445-2b6c9f4]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.11.2-R0.1-SNAPSHOT.jar:git-Spigot-3fb9445-2b6c9f4]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.11.2-R0.1-SNAPSHOT.jar:git-Spigot-3fb9445-2b6c9f4]
	at org.bukkit.craftbukkit.v1_11_R1.event.CraftEventFactory.callPlayerDeathEvent(CraftEventFactory.java:412) [spigot-1.11.2-R0.1-SNAPSHOT.jar:git-Spigot-3fb9445-2b6c9f4]
	at net.minecraft.server.v1_11_R1.EntityPlayer.die(EntityPlayer.java:420) [spigot-1.11.2-R0.1-SNAPSHOT.jar:git-Spigot-3fb9445-2b6c9f4]
	at net.minecraft.server.v1_11_R1.EntityLiving.damageEntity(EntityLiving.java:933) [spigot-1.11.2-R0.1-SNAPSHOT.jar:git-Spigot-3fb9445-2b6c9f4]
	at net.minecraft.server.v1_11_R1.EntityHuman.damageEntity(EntityHuman.java:782) [spigot-1.11.2-R0.1-SNAPSHOT.jar:git-Spigot-3fb9445-2b6c9f4]
	at net.minecraft.server.v1_11_R1.EntityPlayer.damageEntity(EntityPlayer.java:505) [spigot-1.11.2-R0.1-SNAPSHOT.jar:git-Spigot-3fb9445-2b6c9f4]
	at net.minecraft.server.v1_11_R1.EntityMonster.B(EntityMonster.java:68) [spigot-1.11.2-R0.1-SNAPSHOT.jar:git-Spigot-3fb9445-2b6c9f4]
	at net.minecraft.server.v1_11_R1.PathfinderGoalMeleeAttack.a(SourceFile:127) [spigot-1.11.2-R0.1-SNAPSHOT.jar:git-Spigot-3fb9445-2b6c9f4]
	at net.minecraft.server.v1_11_R1.PathfinderGoalMeleeAttack.e(SourceFile:119) [spigot-1.11.2-R0.1-SNAPSHOT.jar:git-Spigot-3fb9445-2b6c9f4]
	at net.minecraft.server.v1_11_R1.PathfinderGoalSelector.a(SourceFile:129) [spigot-1.11.2-R0.1-SNAPSHOT.jar:git-Spigot-3fb9445-2b6c9f4]
	at net.minecraft.server.v1_11_R1.EntityInsentient.doTick(EntityInsentient.java:658) [spigot-1.11.2-R0.1-SNAPSHOT.jar:git-Spigot-3fb9445-2b6c9f4]
	at net.minecraft.server.v1_11_R1.EntityLiving.n(EntityLiving.java:2037) [spigot-1.11.2-R0.1-SNAPSHOT.jar:git-Spigot-3fb9445-2b6c9f4]
	at net.minecraft.server.v1_11_R1.EntityInsentient.n(EntityInsentient.java:501) [spigot-1.11.2-R0.1-SNAPSHOT.jar:git-Spigot-3fb9445-2b6c9f4]
	at net.minecraft.server.v1_11_R1.EntityMonster.n(EntityMonster.java:24) [spigot-1.11.2-R0.1-SNAPSHOT.jar:git-Spigot-3fb9445-2b6c9f4]
	at net.minecraft.server.v1_11_R1.EntityLiving.A_(EntityLiving.java:1893) [spigot-1.11.2-R0.1-SNAPSHOT.jar:git-Spigot-3fb9445-2b6c9f4]
	at net.minecraft.server.v1_11_R1.EntityInsentient.A_(EntityInsentient.java:244) [spigot-1.11.2-R0.1-SNAPSHOT.jar:git-Spigot-3fb9445-2b6c9f4]
	at net.minecraft.server.v1_11_R1.EntityMonster.A_(EntityMonster.java:28) [spigot-1.11.2-R0.1-SNAPSHOT.jar:git-Spigot-3fb9445-2b6c9f4]
	at net.minecraft.server.v1_11_R1.EntitySpider.A_(EntitySpider.java:45) [spigot-1.11.2-R0.1-SNAPSHOT.jar:git-Spigot-3fb9445-2b6c9f4]
	at net.minecraft.server.v1_11_R1.World.entityJoinedWorld(World.java:1631) [spigot-1.11.2-R0.1-SNAPSHOT.jar:git-Spigot-3fb9445-2b6c9f4]
	at net.minecraft.server.v1_11_R1.World.h(World.java:1606) [spigot-1.11.2-R0.1-SNAPSHOT.jar:git-Spigot-3fb9445-2b6c9f4]
	at net.minecraft.server.v1_11_R1.World.tickEntities(World.java:1432) [spigot-1.11.2-R0.1-SNAPSHOT.jar:git-Spigot-3fb9445-2b6c9f4]
	at net.minecraft.server.v1_11_R1.WorldServer.tickEntities(WorldServer.java:618) [spigot-1.11.2-R0.1-SNAPSHOT.jar:git-Spigot-3fb9445-2b6c9f4]
	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:814) [spigot-1.11.2-R0.1-SNAPSHOT.jar:git-Spigot-3fb9445-2b6c9f4]
	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot-1.11.2-R0.1-SNAPSHOT.jar:git-Spigot-3fb9445-2b6c9f4]
	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:678) [spigot-1.11.2-R0.1-SNAPSHOT.jar:git-Spigot-3fb9445-2b6c9f4]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:576) [spigot-1.11.2-R0.1-SNAPSHOT.jar:git-Spigot-3fb9445-2b6c9f4]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_101]
Caused by: java.lang.ClassCastException: me.mrCookieSlime.QuestWorld.quest.Mission cannot be cast to me.mrCookieSlime.QuestWorld.api.Decaying
	at me.mrCookieSlime.QuestWorld.listener.PlayerListener.onDie(PlayerListener.java:51) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_101]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_101]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_101]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_101]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot-1.11.2-R0.1-SNAPSHOT.jar:git-Spigot-3fb9445-2b6c9f4]
	... 29 more`

**Comment by rxsglzc** [comment]
'Resets On Death' problem also in 1.12.2
