### ISSUE TITLE
Idea for a new feature

### ISSUE THREAD

**Issue by Lokarda2** [ezeiger92/QuestWorld2#106]
Hi, would it be possible to add a command, that would open your questbook at 2nd page?

ex. /quests page 2
--> opens categories gui located on the second page

Would be really cool. Thanks

**Comment by Lokarda2** [comment]
also

Could not pass event PlayerDeathEvent to QuestWorld v2.6.10 
org.bukkit.event.EventException: null 
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[server.jar:git-Spigot-7228328-e03b1a5] 
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[server.jar:git-Spigot-7228328-e03b1a5] 
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:499) [server.jar:git-Spigot-7228328-e03b1a5] 
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484) [server.jar:git-Spigot-7228328-e03b1a5] 
at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPlayerDeathEvent(CraftEventFactory.java:412) [server.jar:git-Spigot-7228328-e03b1a5] 
at net.minecraft.server.v1_12_R1.EntityPlayer.die(EntityPlayer.java:423) [server.jar:git-Spigot-7228328-e03b1a5] 
at net.minecraft.server.v1_12_R1.EntityLiving.damageEntity(EntityLiving.java:951) [server.jar:git-Spigot-7228328-e03b1a5] 
at net.minecraft.server.v1_12_R1.EntityHuman.damageEntity(EntityHuman.java:759) [server.jar:git-Spigot-7228328-e03b1a5] 
at net.minecraft.server.v1_12_R1.EntityPlayer.damageEntity(EntityPlayer.java:577) [server.jar:git-Spigot-7228328-e03b1a5] 
at net.minecraft.server.v1_12_R1.EntityHuman.attack(EntityHuman.java:1005) [server.jar:git-Spigot-7228328-e03b1a5] 
at net.minecraft.server.v1_12_R1.EntityPlayer.attack(EntityPlayer.java:1302) [server.jar:git-Spigot-7228328-e03b1a5] 
at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1609) [server.jar:git-Spigot-7228328-e03b1a5] 
at net.minecraft.server.v1_12_R1.PacketPlayInUseEntity.a(SourceFile:69) [server.jar:git-Spigot-7228328-e03b1a5] 
at net.minecraft.server.v1_12_R1.PacketPlayInUseEntity.a(SourceFile:13) [server.jar:git-Spigot-7228328-e03b1a5] 
at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [server.jar:git-Spigot-7228328-e03b1a5] 
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_144] 
at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_144] 
at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [server.jar:git-Spigot-7228328-e03b1a5] 
at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:747) [server.jar:git-Spigot-7228328-e03b1a5] 
at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:405) [server.jar:git-Spigot-7228328-e03b1a5] 
at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:678) [server.jar:git-Spigot-7228328-e03b1a5] 
at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:576) [server.jar:git-Spigot-7228328-e03b1a5] 
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144] 
Caused by: java.lang.ClassCastException: me.mrCookieSlime.QuestWorld.quest.Mission cannot be cast to me.mrCookieSlime.QuestWorld.api.Decaying 
at me.mrCookieSlime.QuestWorld.listener.PlayerListener.onDie(PlayerListener.java:51) ~[QuestWorld-2.6.10%20(1).jar:?] 
at sun.reflect.GeneratedMethodAccessor1246.invoke(Unknown Source) ~[?:?] 
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_144]
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_144] 
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[server.jar:git-Spigot-7228328-e03b1a5]

**Comment by ezeiger92** [comment]
The stacktrace has already been fixed for 2.6.11
