### ISSUE TITLE
Error occurred while enabling QuestWorld v2.6.11

### ISSUE THREAD

**Issue by FilDa196** [ezeiger92/QuestWorld2#107]
Hello, Dear Author
There is a problem with QuestWorld plugin. I'm in spigot-1.11. and QuestWorld-2.6.11 is unabled and write this error.... what is wrong

```
> [12:50:18] [Server thread/ERROR]: Error occurred while enabling QuestWorld v2.6.11 (Is it up to date?)
> java.lang.NoClassDefFoundError: org/bukkit/NamespacedKey
> at me.mrCookieSlime.QuestWorld.GuideBook.<init>(GuideBook.java:20) ~[?:?]
> at me.mrCookieSlime.QuestWorld.GuideBook.instance(GuideBook.java:24) ~[?:?]
> at me.mrCookieSlime.QuestWorld.QuestWorldPlugin.onEnable(QuestWorldPlugin.java:112) ~[?:?]
> at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:271) ~[paperspigot.jar:git-Paper-1104]
> at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316) [paperspigot.jar:git-Paper-1104]
> at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407) [paperspigot.jar:git-Paper-1104]
> at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugin(CraftServer.java:378) [paperspigot.jar:git-Paper-1104]
> at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugins(CraftServer.java:328) [paperspigot.jar:git-Paper-1104]
> at net.minecraft.server.v1_11_R1.MinecraftServer.t(MinecraftServer.java:438) [paperspigot.jar:git-Paper-1104]
> at net.minecraft.server.v1_11_R1.MinecraftServer.l(MinecraftServer.java:399) [paperspigot.jar:git-Paper-1104]
> at net.minecraft.server.v1_11_R1.MinecraftServer.a(MinecraftServer.java:337) [paperspigot.jar:git-Paper-1104]
> at net.minecraft.server.v1_11_R1.DedicatedServer.init(DedicatedServer.java:276) [paperspigot.jar:git-Paper-1104]
> at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:612) [paperspigot.jar:git-Paper-1104]
> at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]
> Caused by: java.lang.ClassNotFoundException: org.bukkit.NamespacedKey
> at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:92) ~[paperspigot.jar:git-Paper-1104]
> at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:87) ~[paperspigot.jar:git-Paper-1104]
> at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_161]
> at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_161]
> ... 14 more
> [12:50:18] [Server thread/INFO]: [QuestWorld] Disabling QuestWorld v2.6.11
```

**Comment by ezeiger92** [comment]
Sorry, but I’m only supporting the latest version of spigot (currently 1.12.2). The class NamespacedKey was added in 1.12, so earlier versions will have that error.

Is there a reason you aren’t using the latest version?

**Comment by FilDa196** [comment]
There's one reason. In older versions I can't write commands in dialogs. I have also tried OP but people with OP can't write commands into dialogues. I thought that it will be fixed in the new version but not.

**Comment by ezeiger92** [comment]
I was asking why you aren't using the latest version of spigot (1.12.2)

**Comment by ezeiger92** [comment]
You could look at [ViaBackwards](https://www.spigotmc.org/resources/viabackwards.27448/) or [ProtocolSupport](https://www.spigotmc.org/resources/protocolsupport.7201/) to allow older clients to join a 1.12.2 server. I'm sure there are others, but those are the only ones I've used.
