### ISSUE TITLE
Failure to create language files on first install

### ISSUE THREAD

**Issue by UltraFaceguy** [ezeiger92/QuestWorld2#114]
Can't generate the folder at all on the latest version. It works if I manually add the directory and en_us.yml

`[19:36:08 INFO]: [QuestWorld] Enabling QuestWorld v2.7.0
[19:36:08 WARN]: java.lang.IllegalArgumentException: Failed read language "lang/en_us.yml"
[19:36:08 WARN]:        at com.questworld.util.Lang.loadLang(Lang.java:58)
[19:36:08 WARN]:        at com.questworld.util.Lang.setLang(Lang.java:71)
[19:36:08 WARN]:        at com.questworld.QuestingImpl.<init>(QuestingImpl.java:68)
[19:36:08 WARN]:        at com.questworld.QuestWorldPlugin.onEnable(QuestWorldPlugin.java:30)
[19:36:08 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[19:36:08 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316)
[19:36:08 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[19:36:08 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:387)
[19:36:08 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:336)
[19:36:08 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:442)
[19:36:08 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:403)
[19:36:08 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:341)
[19:36:08 WARN]:        at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:292)
[19:36:08 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616)
[19:36:08 WARN]:        at java.lang.Thread.run(Unknown Source)
[19:36:08 WARN]: Caused by: java.io.FileNotFoundException: plugins\QuestWorld\lang\en_us.yml (The system cannot find the path specified)
[19:36:08 WARN]:        at java.io.FileOutputStream.open0(Native Method)
[19:36:08 WARN]:        at java.io.FileOutputStream.open(Unknown Source)
[19:36:08 WARN]:        at java.io.FileOutputStream.<init>(Unknown Source)
[19:36:08 WARN]:        at java.io.FileOutputStream.<init>(Unknown Source)
[19:36:08 WARN]:        at com.questworld.util.ResourceLoader.loadConfig(ResourceLoader.java:107)
[19:36:08 WARN]:        at com.questworld.util.Lang.loadLang(Lang.java:55)
[19:36:08 WARN]:        ... 14 more
[19:36:08 INFO]: [SpigotLib] Register service - com.questworld.api.contract.QuestingAPI
[19:36:08 ERROR]: Error occurred while enabling QuestWorld v2.7.0 (Is it up to date?)
java.lang.NullPointerException: null
        at com.questworld.util.Lang.translate(Lang.java:91) ~[?:?]
        at com.questworld.QuestingImpl.translate(QuestingImpl.java:156) ~[?:?]
        at com.questworld.QuestingImpl.translate(QuestingImpl.java:151) ~[?:?]
        at com.questworld.api.QuestWorld.translate(QuestWorld.java:83) ~[?:?]
        at com.questworld.GuideBook.<init>(GuideBook.java:48) ~[?:?]
        at com.questworld.GuideBook.instance(GuideBook.java:25) ~[?:?]
        at com.questworld.QuestWorldPlugin.onEnable(QuestWorldPlugin.java:45) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[patched_1.12.2.jar:git-Paper-1322]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316) [patched_1.12.2.jar:git-Paper-1322]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [patched_1.12.2.jar:git-Paper-1322]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:387) [patched_1.12.2.jar:git-Paper-1322]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:336) [patched_1.12.2.jar:git-Paper-1322]
        at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:442) [patched_1.12.2.jar:git-Paper-1322]
        at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:403) [patched_1.12.2.jar:git-Paper-1322]
        at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:341) [patched_1.12.2.jar:git-Paper-1322]
        at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:292) [patched_1.12.2.jar:git-Paper-1322]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616) [patched_1.12.2.jar:git-Paper-1322]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_111]
[19:36:08 INFO]: [QuestWorld] Disabling QuestWorld v2.7.0`

**Comment by ezeiger92** [comment]
`Enabling QuestWorld v2.7.0` Using the current version (2.6.13) I cannot replicate this issue.
