### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Star-Marks** [ezeiger92/QuestWorld2#121]
A serious error occurred when I ran /qe book Star_marks

> Star_marks issued server command: /qe book Star_marks
[13:06:33 错误]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'qe' in plugin QuestWorld v2.6.13
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[Start.jar:git-Spigot-7d78b81-7e19325]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[Start.jar:git-Spigot-7d78b81-7e19325]
	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.dispatchCommand(CraftServer.java:649) ~[Start.jar:git-Spigot-7d78b81-7e19325]
	at net.minecraft.server.v1_11_R1.PlayerConnection.handleCommand(PlayerConnection.java:1344) [Start.jar:git-Spigot-7d78b81-7e19325]
	at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:1179) [Start.jar:git-Spigot-7d78b81-7e19325]
	at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [Start.jar:git-Spigot-7d78b81-7e19325]
	at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [Start.jar:git-Spigot-7d78b81-7e19325]
	at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13) [Start.jar:git-Spigot-7d78b81-7e19325]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_171]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_171]
	at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46) [Start.jar:git-Spigot-7d78b81-7e19325]
	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:739) [Start.jar:git-Spigot-7d78b81-7e19325]
	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [Start.jar:git-Spigot-7d78b81-7e19325]
	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:675) [Start.jar:git-Spigot-7d78b81-7e19325]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:574) [Start.jar:git-Spigot-7d78b81-7e19325]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_171]
Caused by: java.lang.NoClassDefFoundError: org/bukkit/NamespacedKey
	at me.mrCookieSlime.QuestWorld.GuideBook.<init>(GuideBook.java:20) ~[?:?]
	at me.mrCookieSlime.QuestWorld.GuideBook.instance(GuideBook.java:24) ~[?:?]
	at me.mrCookieSlime.QuestWorld.command.EditorCommand.onCommand(EditorCommand.java:101) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[Start.jar:git-Spigot-7d78b81-7e19325]
	... 15 more

**Comment by ezeiger92** [comment]
You are using an old server version that I do not support (1.11.x). Is there a reason you haven't updated to 1.12 / 1.12.2?

**Comment by Star-Marks** [comment]
If I want to use it at 1.11.x, which version should I download?

**Comment by Star-Marks** [comment]
I tested it, it can be run, thank you very much

**Comment by ezeiger92** [comment]
Glad to help ^^
