### ISSUE TITLE
Something is wrong with spigot 1.12.2. Could you help me?

### ISSUE THREAD

**Issue by thtTNT** [ezeiger92/QuestWorld2#124]
I don't know what causes this error. I just translate it. If you see this issues, could you help us? This plugin is very important for us. Now we clone this project then use 2.7.0 instead.

Here it's environment:
OS: Windows server 2012
JAVA: JAVA8
MinecraftServerVersion: spigot 1.12.2-latest

Thank you for your time! Have a good day.
 

[11:21:23] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to QuestWorld v2.6.13
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.12.2.jar:git-Spigot-642f6d2-6103339]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.12.2.jar:git-Spigot-642f6d2-6103339]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [spigot-1.12.2.jar:git-Spigot-642f6d2-6103339]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) [spigot-1.12.2.jar:git-Spigot-642f6d2-6103339]
	at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:235) [spigot-1.12.2.jar:git-Spigot-642f6d2-6103339]
	at net.minecraft.server.v1_12_R1.PlayerInteractManager.a(PlayerInteractManager.java:458) [spigot-1.12.2.jar:git-Spigot-642f6d2-6103339]
	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:951) [spigot-1.12.2.jar:git-Spigot-642f6d2-6103339]
	at net.minecraft.server.v1_12_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:37) [spigot-1.12.2.jar:git-Spigot-642f6d2-6103339]
	at net.minecraft.server.v1_12_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:1) [spigot-1.12.2.jar:git-Spigot-642f6d2-6103339]
	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.12.2.jar:git-Spigot-642f6d2-6103339]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_171]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_171]
	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [spigot-1.12.2.jar:git-Spigot-642f6d2-6103339]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748) [spigot-1.12.2.jar:git-Spigot-642f6d2-6103339]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot-1.12.2.jar:git-Spigot-642f6d2-6103339]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot-1.12.2.jar:git-Spigot-642f6d2-6103339]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot-1.12.2.jar:git-Spigot-642f6d2-6103339]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_171]
Caused by: java.lang.ClassCastException: me.mrCookieSlime.QuestWorld.quest.Category cannot be cast to me.mrCookieSlime.QuestWorld.api.contract.IStateful
	at me.mrCookieSlime.QuestWorld.api.menu.QuestBook.lambda$getLastViewed$0(QuestBook.java:42) ~[?:?]
	at java.util.Optional.map(Unknown Source) ~[?:1.8.0_171]
	at me.mrCookieSlime.QuestWorld.api.menu.QuestBook.getLastViewed(QuestBook.java:42) ~[?:?]
	at me.mrCookieSlime.QuestWorld.api.menu.QuestBook.openLastMenu(QuestBook.java:139) ~[?:?]
	at me.mrCookieSlime.QuestWorld.listener.PlayerListener.onQuestBook(PlayerListener.java:41) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor477.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_171]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_171]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot-1.12.2.jar:git-Spigot-642f6d2-6103339]
	... 17 more

**Comment by ezeiger92** [comment]
That error should not be possible given the 2.6.13 release, did you download the plugin from here or build it yourself?

**Comment by ezeiger92** [comment]
Better question: Did you reload the server through /reload or a plugin like PlugMan before that error came up? QuestWorld is not reload safe at all.

**Comment by thtTNT** [comment]
Thanks for your help. As you said. We use /reload command to reload this plugin. It might cause this problem. I would try it later. Thanks for your help again!

**Comment by ezeiger92** [comment]
Glad to help! I'm slowly making QuestWorld more reload safe, but I don't think it will ever be completely safe.
I'll close this ticket for now, if you (somehow) have this issue again without reloading, post back in here and I can reopen it.
