### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by BaiYeLoser** [ezeiger92/QuestWorld2#135]
[19:12:01 ERROR]: Error occurred while enabling QuestWorld v2.6.13 (Is it up to date?)
java.lang.IllegalStateException: Duplicate recipe ignored with ID questworld:guidebook
        at net.minecraft.server.v1_12_R1.CraftingManager.a(CraftingManager.java:149) ~[1.12.2.jar:git-Spigot-d21162c-82f3b02]
        at org.bukkit.craftbukkit.v1_12_R1.inventory.CraftShapelessRecipe.addToCraftingManager(CraftShapelessRecipe.java:46) ~[1.12.2.jar:git-Spigot-d21162c-82f3b02]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.addRecipe(CraftServer.java:1099) ~[1.12.2.jar:git-Spigot-d21162c-82f3b02]
        at me.mrCookieSlime.QuestWorld.QuestWorldPlugin.onEnable(QuestWorldPlugin.java:112) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[1.12.2.jar:git-Spigot-d21162c-82f3b02]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [1.12.2.jar:git-Spigot-d21162c-82f3b02]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403) [1.12.2.jar:git-Spigot-d21162c-82f3b02]
        at com.rylinaux.plugman.util.PluginUtil.load(PluginUtil.java:366) [PlugMan+2.1.3+-+1.11.jar:?]
        at com.rylinaux.plugman.command.LoadCommand.execute(LoadCommand.java:114) [PlugMan+2.1.3+-+1.11.jar:?]
        at com.rylinaux.plugman.PlugManCommandHandler.onCommand(PlugManCommandHandler.java:95) [PlugMan+2.1.3+-+1.11.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) [1.12.2.jar:git-Spigot-d21162c-82f3b02]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) [1.12.2.jar:git-Spigot-d21162c-82f3b02]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:651) [1.12.2.jar:git-Spigot-d21162c-82f3b02]
        at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1397) [1.12.2.jar:git-Spigot-d21162c-82f3b02]
        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1232) [1.12.2.jar:git-Spigot-d21162c-82f3b02]
        at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [1.12.2.jar:git-Spigot-d21162c-82f3b02]
        at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [1.12.2.jar:git-Spigot-d21162c-82f3b02]
        at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [1.12.2.jar:git-Spigot-d21162c-82f3b02]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_66]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_66]
        at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [1.12.2.jar:git-Spigot-d21162c-82f3b02]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748) [1.12.2.jar:git-Spigot-d21162c-82f3b02]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [1.12.2.jar:git-Spigot-d21162c-82f3b02]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [1.12.2.jar:git-Spigot-d21162c-82f3b02]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [1.12.2.jar:git-Spigot-d21162c-82f3b02]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_66]

spigot-1.12.2 Why?2.6.13version

**Comment by ezeiger92** [comment]
`Duplicate recipe ignored with ID questworld:guidebooK`
...
`com.rylinaux.plugman.util.PluginUtil.load`

QuestWorld does not support reloading through /reload or plugins like PlugMan. Use /qe reload to update all config files or /qe discard to revert all quest and player data to the files on disk.
