### ISSUE TITLE
QuestWorld 2.8.0a2 Issues

### ISSUE THREAD

**Issue by Peculiarityy** [ezeiger92/QuestWorld2#151]
After upgrading to **QuestWorld 2.8.0a2** whenever opening the Quests GUI, editor etc. the error below is printed out. The mission updates from the previous alpha deleted all mission types.

```22.01 01:46:53 [Server] WARN java.lang.NullPointerException
22.01 01:46:53 [Server] WARN at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:68)
22.01 01:46:53 [Server] WARN at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:46)
22.01 01:46:53 [Server] WARN at com.questworld.util.ItemBuilder.<init>(ItemBuilder.java:146)
22.01 01:46:53 [Server] WARN at com.questworld.api.menu.QuestBook.openQuestEditor(QuestBook.java:1078)
22.01 01:46:53 [Server] WARN at com.questworld.api.menu.Buttons.lambda$onQuest$3(Buttons.java:60)
22.01 01:46:53 [Server] WARN at com.questworld.api.menu.PagedMapping.lambda$addButton$0(PagedMapping.java:111)
22.01 01:46:53 [Server] WARN at com.questworld.api.menu.Menu.click(Menu.java:96)
22.01 01:46:53 [Server] WARN at com.questworld.listener.MenuListener.onInventoryClick(MenuListener.java:33)
22.01 01:46:53 [Server] WARN at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
22.01 01:46:53 [Server] WARN at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
22.01 01:46:53 [Server] WARN at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
22.01 01:46:53 [Server] WARN at java.lang.reflect.Method.invoke(Method.java:498)
22.01 01:46:53 [Server] WARN at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302)
22.01 01:46:53 [Server] WARN at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
22.01 01:46:53 [Server] WARN at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500)
22.01 01:46:53 [Server] WARN at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485)
22.01 01:46:53 [Server] WARN at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1889)
22.01 01:46:53 [Server] WARN at net.minecraft.server.v1_12_R1.PacketPlayInWindowClick.a(SourceFile:33)
22.01 01:46:53 [Server] WARN at net.minecraft.server.v1_12_R1.PacketPlayInWindowClick.a(SourceFile:10)
22.01 01:46:53 [Server] WARN at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13)
22.01 01:46:53 [Server] WARN at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
22.01 01:46:53 [Server] WARN at java.util.concurrent.FutureTask.run(FutureTask.java:266)
22.01 01:46:53 [Server] WARN at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46)
22.01 01:46:53 [Server] WARN at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748)
22.01 01:46:53 [Server] WARN at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406)
22.01 01:46:53 [Server] WARN at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679)
22.01 01:46:53 [Server] WARN at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577)
22.01 01:46:53 [Server] WARN at java.lang.Thread.run(Thread.java:748)```

**Comment by ezeiger92** [comment]
Alpha3 is out now, make sure you use QW-Legacy when running 1.12.2
