### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Arrandirs** [ezeiger92/QuestWorld2#152]
Hello i have this issue 
```
Could not pass event PlayerInteractEvent to QuestWorld v2.7.0
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot.jar:git-Spigot-dcd1643-e60fc34]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-dcd1643-e60fc34]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [spigot.jar:git-Spigot-dcd1643-e60fc34]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) [spigot.jar:git-Spigot-dcd1643-e60fc34]
	at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:235) [spigot.jar:git-Spigot-dcd1643-e60fc34]
	at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:202) [spigot.jar:git-Spigot-dcd1643-e60fc34]
	at net.minecraft.server.v1_12_R1.BlockPressurePlateBinary.e(BlockPressurePlateBinary.java:75) [spigot.jar:git-Spigot-dcd1643-e60fc34]
	at net.minecraft.server.v1_12_R1.BlockPressurePlateAbstract.a(BlockPressurePlateAbstract.java:96) [spigot.jar:git-Spigot-dcd1643-e60fc34]
	at net.minecraft.server.v1_12_R1.BlockPressurePlateAbstract.a(BlockPressurePlateAbstract.java:89) [spigot.jar:git-Spigot-dcd1643-e60fc34]
	at net.minecraft.server.v1_12_R1.Entity.checkBlockCollisions(Entity.java:963) [spigot.jar:git-Spigot-dcd1643-e60fc34]
	at net.minecraft.server.v1_12_R1.Entity.move(Entity.java:543) [spigot.jar:git-Spigot-dcd1643-e60fc34]
	at net.minecraft.server.v1_12_R1.EntityLiving.a(EntityLiving.java:1813) [spigot.jar:git-Spigot-dcd1643-e60fc34]
	at net.minecraft.server.v1_12_R1.EntityHuman.a(EntityHuman.java:1426) [spigot.jar:git-Spigot-dcd1643-e60fc34]
	at net.citizensnpcs.nms.v1_12_R1.entity.EntityHumanNPC.a(EntityHumanNPC.java:120) [Citizens-2.0.24-b1604.jar:?]
	at net.citizensnpcs.nms.v1_12_R1.entity.EntityHumanNPC.B_(EntityHumanNPC.java:150) [Citizens-2.0.24-b1604.jar:?]
	at net.minecraft.server.v1_12_R1.World.entityJoinedWorld(World.java:1631) [spigot.jar:git-Spigot-dcd1643-e60fc34]
	at net.citizensnpcs.nms.v1_12_R1.util.NMSImpl.tick(NMSImpl.java:1015) [Citizens-2.0.24-b1604.jar:?]
	at net.citizensnpcs.util.NMS.tick(NMS.java:318) [Citizens-2.0.24-b1604.jar:?]
	at net.citizensnpcs.util.PlayerUpdateTask.run(PlayerUpdateTask.java:36) [Citizens-2.0.24-b1604.jar:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76) [spigot.jar:git-Spigot-dcd1643-e60fc34]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:361) [spigot.jar:git-Spigot-dcd1643-e60fc34]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:739) [spigot.jar:git-Spigot-dcd1643-e60fc34]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot.jar:git-Spigot-dcd1643-e60fc34]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot.jar:git-Spigot-dcd1643-e60fc34]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot.jar:git-Spigot-dcd1643-e60fc34]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
Caused by: java.lang.IllegalArgumentException: Player null (d2395d9e-142b-23a9-bde6-c65ff6299d35) is offline
	at com.questworld.manager.PlayerStatus.asOnline(PlayerStatus.java:77) ~[?:?]
	at com.questworld.manager.PlayerStatus.getStatus(PlayerStatus.java:177) ~[?:?]
	at com.questworld.manager.PlayerStatus.isMissionActive(PlayerStatus.java:132) ~[?:?]
	at com.questworld.manager.MissionSet$MissionEntryIterator.next(MissionSet.java:75) ~[?:?]
	at com.questworld.manager.MissionSet$MissionEntryIterator.<init>(MissionSet.java:60) ~[?:?]
	at com.questworld.manager.MissionSet.iterator(MissionSet.java:88) ~[?:?]
	at com.questworld.extension.extras.ClickBlockMission.onInteract(ClickBlockMission.java:84) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor134.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_181]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_181]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot.jar:git-Spigot-dcd1643-e60fc34]
	... 25 more
```

**Comment by Arrandirs** [comment]
but i not reload the server :/ 
i use the normal method to stop the server.

**Comment by ezeiger92** [comment]
Hah! A citizens NPC stepped on a pressure plate and sent off a PlayerInteractEvent. Did not know non-players could send that.

**Comment by Arrandirs** [comment]
i try to remove every things on my questworld's folders. 
I found 2-3 files category who create this error
but i don't know why :/ they have same things than the other files who create no problem :/

**Comment by Arrandirs** [comment]
I have this error on flat map too :/

**Comment by Arrandirs** [comment]
A map where i have no npc :(

**Comment by Arrandirs** [comment]
what can i do :( ? 
this is one of the files who have this error who are created when i start the server:
uniqueId: 02857e82-ac04-4301-9858-ec1faac70290
id: 1
name: '&bIntroduction'
item:
  ==: org.bukkit.inventory.ItemStack
  type: TOTEM
permission: ''
hidden: false
world-blacklist: []

and one who create no problem:
uniqueId: 417a324b-ee9d-4068-860e-97fbf3fe9120
id: 2
name: '&2Survivre dans la nature'
item:
  ==: org.bukkit.inventory.ItemStack
  type: LONG_GRASS
  damage: 1
permission: ''
hidden: false
world-blacklist: []
parentId: d8cce0bb-539f-43d3-9e0a-b917d7f5d3cf

Like we can see, i see no difference except the id

**Comment by Arrandirs** [comment]
I try to use the plugin without any others but the errors are same.

**Comment by ezeiger92** [comment]
`/npc list -a` should show you all NPCs on your server, one of them hit a pressure plate and triggered this bug. `/npc select [id]` and `/npc tp` should take you to that NPC.

**Comment by Arrandirs** [comment]
I try every npc. I tp every npc to me but the bug continue :(

**Comment by Arrandirs** [comment]
Ok i found ! Is it a pressure plate like you said but the pressure plate need to have more than 1 bloc or he create the bug :D thank you :D
