### ISSUE TITLE
1.10

### ISSUE THREAD

**Issue by megaintel** [ezeiger92/QuestWorld2#161]
the plugin is compatible for 1.10 would pass me a link to download the plugin.

**Comment by ezeiger92** [comment]
Use the latest version and put the Legacy extension (https://github.com/ezeiger92/QuestWorld-Legacy) in your QuestWorld extensions folder.

**Comment by megaintel** [comment]
puede enseñar con un video como descarg y ponerlo profavor?

**Comment by megaintel** [comment]
me sale este error 
> [14:02:43 WARN]: [QuestWorld] Task #587 for QuestWorld v2.6.6 generated an exception
java.lang.NoClassDefFoundError: me/mrCookieSlime/CSCoreLibPlugin/general/Particles/MC_1_8/ParticleEffect
at me.mrCookieSlime.QuestWorld.hooks.citizens.CitizensHook$1.run(CitizensHook.java:88) ~[?:?]
at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.10-R0.1-SNAPSHOT-latest.jar:git-Spigot-6016ac7-10c10b3]
at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot-1.10-R0.1-SNAPSHOT-latest.jar:git-Spigot-6016ac7-10c10b3]
at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:741) [spigot-1.10-R0.1-SNAPSHOT-latest.jar:git-Spigot-6016ac7-10c10b3]
at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot-1.10-R0.1-SNAPSHOT-latest.jar:git-Spigot-6016ac7-10c10b3]
at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:672) [spigot-1.10-R0.1-SNAPSHOT-latest.jar:git-Spigot-6016ac7-10c10b3]
at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:571) [spigot-1.10-R0.1-SNAPSHOT-latest.jar:git-Spigot-6016ac7-10c10b3]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]

**Comment by megaintel** [comment]
mrCookieSlime/CSCoreLibPlugin/general/Particles/MC_1_8/ParticleEffect

**Comment by ezeiger92** [comment]
2.6.6 is not the latest version.


> 
2.6.6 is not the latest version
> Use the latest version and put the Legacy extension (https://github.com/ezeiger92/QuestWorld-Legacy) in your QuestWorld extensions folder.
