### ISSUE TITLE
1.16.3 Tuinity bug report

### ISSUE THREAD

**Issue by MrTangsr** [ezeiger92/QuestWorld2#166]
I use QuestWorld-2.8.1-SNAPSHOT on my 1.16.3 [tuinity](https://github.com/Spottedleaf/Tuinity) server. When I edit "Mission list" and add kill mission. It can't change entity type. "An internal problem occurred" log here.
```
[23:09:29 WARN]: java.lang.NullPointerException
[23:09:29 WARN]:        at com.questworld.util.ItemBuilder.wrapText(ItemBuilder.java:336)
[23:09:29 WARN]:        at com.questworld.api.menu.QBDialogue.openQuestMissionEntityEditor(QBDialogue.java:141)
[23:09:29 WARN]:        at com.questworld.api.menu.MissionButton.lambda$2(MissionButton.java:83)
[23:09:29 WARN]:        at com.questworld.api.menu.Menu.click(Menu.java:104)
[23:09:29 WARN]:        at com.questworld.listener.MenuListener.onInventoryClick(MenuListener.java:33)
[23:09:29 WARN]:        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor113.execute(Unknown Source)
[23:09:29 WARN]:        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69)
[23:09:29 WARN]:        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[23:09:29 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[23:09:29 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607)
[23:09:29 WARN]:        at net.minecraft.server.v1_16_R2.PlayerConnection.a(PlayerConnection.java:2440)
[23:09:29 WARN]:        at net.minecraft.server.v1_16_R2.PacketPlayInWindowClick.a(SourceFile:32)
[23:09:29 WARN]:        at net.minecraft.server.v1_16_R2.PacketPlayInWindowClick.a(SourceFile:10)
[23:09:29 WARN]:        at net.minecraft.server.v1_16_R2.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:43)
[23:09:29 WARN]:        at net.minecraft.server.v1_16_R2.TickTask.run(SourceFile:18)
[23:09:29 WARN]:        at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136)
[23:09:29 WARN]:        at net.minecraft.server.v1_16_R2.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
[23:09:29 WARN]:        at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109)
[23:09:29 WARN]:        at net.minecraft.server.v1_16_R2.MinecraftServer.ba(MinecraftServer.java:1190)
[23:09:29 WARN]:        at net.minecraft.server.v1_16_R2.MinecraftServer.executeNext(MinecraftServer.java:1183)
[23:09:29 WARN]:        at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119)
[23:09:29 WARN]:        at net.minecraft.server.v1_16_R2.MinecraftServer.sleepForTick(MinecraftServer.java:1159)
[23:09:29 WARN]:        at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:1003)
[23:09:29 WARN]:        at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177)
[23:09:29 WARN]:        at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by ezeiger92** [comment]
What entity were you trying to use?
That version of code looks for "{entity name}_SPAWN_EGG", and if it cannot be found sends back Material.AIR. Air does not support metadata, and throws that exception
