### ISSUE TITLE
1.12

### ISSUE THREAD

**Issue by erik1988** [ezeiger92/QuestWorld2#19]
Im getting this when the plugin is trying to save in 1.12
im using: QuestWorld 2.6.3

`[13:02:26] [Server thread/ERROR]: null
net.minecraft.server.v1_12_R1.MojangsonParseException: Expected '}' but got ':' at: {EntityTag:{id:minecraft:<--[HERE]
	at net.minecraft.server.v1_12_R1.MojangsonParser.b(SourceFile:315) ~[patched_1.12.jar:git-Paper-1111]
	at net.minecraft.server.v1_12_R1.MojangsonParser.f(SourceFile:198) ~[patched_1.12.jar:git-Paper-1111]
	at net.minecraft.server.v1_12_R1.MojangsonParser.d(SourceFile:160) ~[patched_1.12.jar:git-Paper-1111]
	at net.minecraft.server.v1_12_R1.MojangsonParser.f(SourceFile:190) ~[patched_1.12.jar:git-Paper-1111]
	at net.minecraft.server.v1_12_R1.MojangsonParser.a(SourceFile:34) ~[patched_1.12.jar:git-Paper-1111]
	at net.minecraft.server.v1_12_R1.MojangsonParser.parse(SourceFile:29) ~[patched_1.12.jar:git-Paper-1111]
	at org.bukkit.craftbukkit.v1_12_R1.util.CraftMagicNumbers.modifyItemStack(CraftMagicNumbers.java:130) ~[patched_1.12.jar:git-Paper-1111]
	at me.mrCookieSlime.QuestWorld.utils.ItemBuilder.tag(ItemBuilder.java:248) ~[?:?]
	at me.mrCookieSlime.QuestWorld.utils.ItemBuilder.mob(ItemBuilder.java:262) ~[?:?]
	at me.mrCookieSlime.QuestWorld.quests.QuestMission.getItem(QuestMission.java:114) ~[?:?]
	at me.mrCookieSlime.QuestWorld.quests.Quest.save(Quest.java:169) ~[?:?]
	at me.mrCookieSlime.QuestWorld.quests.Category.save(Category.java:82) ~[?:?]
	at me.mrCookieSlime.QuestWorld.QuestWorld.save(QuestWorld.java:396) ~[?:?]
	at me.mrCookieSlime.QuestWorld.QuestWorld.exportPreset(QuestWorld.java:461) ~[?:?]
	at me.mrCookieSlime.QuestWorld.commands.EditorCommand.onCommand(EditorCommand.java:57) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[patched_1.12.jar:git-Paper-1111]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:151) ~[patched_1.12.jar:git-Paper-1111]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:669) ~[patched_1.12.jar:git-Paper-1111]
	at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1424) ~[patched_1.12.jar:git-Paper-1111]
	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1229) ~[patched_1.12.jar:git-Paper-1111]
	at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[patched_1.12.jar:git-Paper-1111]
	at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.12.jar:git-Paper-1111]
	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14) ~[patched_1.12.jar:git-Paper-1111]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_131]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_131]
	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [patched_1.12.jar:git-Paper-1111]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:839) [patched_1.12.jar:git-Paper-1111]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:409) [patched_1.12.jar:git-Paper-1111]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:763) [patched_1.12.jar:git-Paper-1111]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:661) [patched_1.12.jar:git-Paper-1111]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
[13:02:26] [Server thread/ERROR]: null`

**Comment by erik1988** [comment]
This error disappeared when I build the project with 1.12. 

However I now have another error:
`[16:37:44] [Server thread/ERROR]: Could not pass event ItemUseEvent to QuestWorld v2.6.3
org.bukkit.event.EventException: null
	at org.bukkit.plugin.EventExecutor$1.execute(EventExecutor.java:46) ~[patched_1.12.jar:git-Paper-1111]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.12.jar:git-Paper-1111]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.12.jar:git-Paper-1111]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:514) ~[patched_1.12.jar:git-Paper-1111]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:499) ~[patched_1.12.jar:git-Paper-1111]
	at me.mrCookieSlime.CSCoreLibPlugin.events.Listeners.ItemUseListener.onRightClick(ItemUseListener.java:23) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor171.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$1.execute(EventExecutor.java:44) ~[patched_1.12.jar:git-Paper-1111]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.12.jar:git-Paper-1111]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.12.jar:git-Paper-1111]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:514) ~[patched_1.12.jar:git-Paper-1111]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:499) ~[patched_1.12.jar:git-Paper-1111]
	at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:235) ~[patched_1.12.jar:git-Paper-1111]
	at net.minecraft.server.v1_12_R1.PlayerInteractManager.a(PlayerInteractManager.java:448) ~[patched_1.12.jar:git-Paper-1111]
	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:948) ~[patched_1.12.jar:git-Paper-1111]
	at net.minecraft.server.v1_12_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:37) ~[patched_1.12.jar:git-Paper-1111]
	at net.minecraft.server.v1_12_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:5) ~[patched_1.12.jar:git-Paper-1111]
	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14) ~[patched_1.12.jar:git-Paper-1111]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_131]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_131]
	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [patched_1.12.jar:git-Paper-1111]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:839) [patched_1.12.jar:git-Paper-1111]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:409) [patched_1.12.jar:git-Paper-1111]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:763) [patched_1.12.jar:git-Paper-1111]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:661) [patched_1.12.jar:git-Paper-1111]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
Caused by: java.lang.NullPointerException
	at me.mrCookieSlime.QuestWorld.GuideBook.isSimilar(GuideBook.java:24) ~[?:?]
	at me.mrCookieSlime.QuestWorld.listeners.PlayerListener.onQuestBook(PlayerListener.java:30) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor500.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$1.execute(EventExecutor.java:44) ~[patched_1.12.jar:git-Paper-1111]
	... 25 more`

**Comment by erik1988** [comment]
I guess its due to the changes in ShapelessRecipe.

**Comment by ezeiger92** [comment]
I can put out a build that fixes this, but it's likely to have some other issues because I haven't properly tested a bunch of changes. The stuff we're using it for all works, but keep an eye out!

**Comment by erik1988** [comment]
Thank you that would be great!
I will let you know if I find any other issues.

**Comment by ezeiger92** [comment]
And here's the build https://github.com/ezeiger92/QuestWorld2/releases/tag/v2.6.4-beta
