### ISSUE TITLE
Error message in console with new 2.6.5

### ISSUE THREAD

**Issue by Dalsok** [ezeiger92/QuestWorld2#25]
```
[11:33:14] [Server thread/ERROR]: [QuestWorld] I did not know this was possible, falling back to MaterialData comparison this time
[11:33:14] [Server thread/ERROR]: [QuestWorld] Lost ability to reflect "pickBlock" method when we previously could!
[11:33:14] [Server thread/WARN]: java.lang.reflect.InvocationTargetException
[11:33:14] [Server thread/WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[11:33:14] [Server thread/WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[11:33:14] [Server thread/WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[11:33:14] [Server thread/WARN]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[11:33:14] [Server thread/WARN]: 	at me.mrCookieSlime.QuestWorld.utils.PlayerTools$Reflector.pickBlock(PlayerTools.java:105)
[11:33:14] [Server thread/WARN]: 	at me.mrCookieSlime.QuestWorld.utils.PlayerTools.getStackOf(PlayerTools.java:135)
[11:33:14] [Server thread/WARN]: 	at me.mrCookieSlime.QuestWorld.hooks.builtin.MineMission.onMine(MineMission.java:39)
[11:33:14] [Server thread/WARN]: 	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1061.execute(Unknown Source)
[11:33:14] [Server thread/WARN]: 	at org.bukkit.plugin.EventExecutor$1.execute(EventExecutor.java:44)
[11:33:14] [Server thread/WARN]: 	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78)
[11:33:14] [Server thread/WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[11:33:14] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:514)
[11:33:14] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:499)
[11:33:14] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PlayerInteractManager.breakBlock(PlayerInteractManager.java:289)
[11:33:14] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PlayerInteractManager.a(PlayerInteractManager.java:216)
[11:33:14] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:885)
[11:33:14] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PacketPlayInBlockDig.a(SourceFile:40)
[11:33:14] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PacketPlayInBlockDig.a(SourceFile:10)
[11:33:14] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14)
[11:33:14] [Server thread/WARN]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[11:33:14] [Server thread/WARN]: 	at java.util.concurrent.FutureTask.run(Unknown Source)
[11:33:14] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46)
[11:33:14] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:842)
[11:33:14] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:416)
[11:33:14] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:766)
[11:33:14] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:664)
[11:33:14] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)
[11:33:14] [Server thread/WARN]: Caused by: java.lang.NullPointerException
[11:33:14] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.BlockShulkerBox.a(BlockShulkerBox.java:182)
[11:33:14] [Server thread/WARN]: 	... 27 more
[11:33:14] [Server thread/ERROR]: [QuestWorld] Block was: {type=PURPLE_SHULKER_BOX, damage=1}
```

**Comment by ezeiger92** [comment]
Okay, so when I fixed #20, I didn't. :/
Short version is I'm dumb and can't read, fixing.

**Comment by ezeiger92** [comment]
Well this one was a ride. A really dumb ride. Whatever, all should be fixed. I replaced the 2.6.5 release with a new one fixing this issue. Grab the new one and make sure I didn't screw it up again D:

**Comment by Dalsok** [comment]
Ah i failed to se this befor now :-9 will try this out.

**Comment by ezeiger92** [comment]
Oh lol! Sorry mate, hope it works now
