### ISSUE TITLE
Error message when a player deleted a party

### ISSUE THREAD

**Issue by Dalsok** [ezeiger92/QuestWorld2#34]
So a player was deleting a party, got to keep the Red wool and i got this message in console
```
[22:13:07] [Server thread/ERROR]: Could not pass event InventoryClickEvent to CS-CoreLib v1.5.16
org.bukkit.event.EventException: null
	at org.bukkit.plugin.EventExecutor$1.execute(EventExecutor.java:46) ~[paper.jar:git-Paper-1124]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[paper.jar:git-Paper-1124]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[paper.jar:git-Paper-1124]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:514) ~[paper.jar:git-Paper-1124]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:499) ~[paper.jar:git-Paper-1124]
	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1933) ~[paper.jar:git-Paper-1124]
	at net.minecraft.server.v1_12_R1.PacketPlayInWindowClick.a(SourceFile:33) ~[paper.jar:git-Paper-1124]
	at net.minecraft.server.v1_12_R1.PacketPlayInWindowClick.a(SourceFile:10) ~[paper.jar:git-Paper-1124]
	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14) ~[paper.jar:git-Paper-1124]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_131]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_131]
	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [paper.jar:git-Paper-1124]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:842) [paper.jar:git-Paper-1124]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423) [paper.jar:git-Paper-1124]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:766) [paper.jar:git-Paper-1124]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:664) [paper.jar:git-Paper-1124]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_131]
Caused by: java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.nextNode(Unknown Source) ~[?:1.8.0_131]
	at java.util.HashMap$KeyIterator.next(Unknown Source) ~[?:1.8.0_131]
	at me.mrCookieSlime.QuestWorld.parties.Party.abandon(Party.java:110) ~[?:?]
	at me.mrCookieSlime.QuestWorld.quests.QuestBook$15.onClick(QuestBook.java:292) ~[?:?]
	at me.mrCookieSlime.CSCoreLibPlugin.events.Listeners.MenuClickListener.onClick(MenuClickListener.java:33) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor306.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$1.execute(EventExecutor.java:44) ~[paper.jar:git-Paper-1124]
	... 16 more
```
spigot 1.12
Questworld 2.6.6
CS_Corelib 1.5.15

**Comment by ezeiger92** [comment]
This is probably ezeiger92/QuestWorld2#7, except with a stacktrace :D. I'll take a look when I get some time, thanks!

**Comment by ezeiger92** [comment]
```java
for (UUID member: members)
        members.remove(member);
```
Modifying a container in a foreach loop... Yep, that would throw.
