### ISSUE TITLE
[CRITICAL] Error after deleting quests and quest groups

### ISSUE THREAD

**Issue by Tarka-Dhal** [ezeiger92/QuestWorld2#88]
Sometimes after deleting quests or quest groups plugin throws this task issue:

`[QuestWorld] Task #93 for QuestWorld v2.6.8 generated an exception
java.lang.NullPointerException
at me.mrCookieSlime.QuestWorld.extensions.builtin.LocationMission.onManual(LocationMission.java:67) ~[QuestWorld-2.6.8.jar:?]
at me.mrCookieSlime.QuestWorld.api.Ticking.onTick(Ticking.java:9) ~[QuestWorld-2.6.8.jar:?]
at me.mrCookieSlime.QuestWorld.managers.PlayerManager.update(PlayerManager.java:174) ~[QuestWorld-2.6.8.jar:?]
at me.mrCookieSlime.QuestWorld.QuestWorld$2.run(QuestWorld.java:165) ~[QuestWorld-2.6.8.jar:?]
at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:58) ~[paperspigot.jar:git-Paper-1104]
at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:356) [paperspigot.jar:git-Paper-1104]
at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:829) [paperspigot.jar:git-Paper-1104]
at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:403) [paperspigot.jar:git-Paper-1104]
at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:763) [paperspigot.jar:git-Paper-1104]
at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:661) [paperspigot.jar:git-Paper-1104]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]`

After it, all server functions like teleporting, signs, etc.. doesn't work.

**Comment by Zicerite** [comment]
Try on the newest version, as your version is old

**Comment by ezeiger92** [comment]
I’m gonna need a full log file if you want this looked into
